global using Microsoft.AspNetCore.Identity;
global using System.ComponentModel.DataAnnotations;
global using JWT.Models;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using JWT.Data;
global using JWT.Services;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;